/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfoRouteImport } from './routes/info'
import { Route as KavaRouteImport } from './routes/kava'
import { Route as KoolitajadRouteImport } from './routes/koolitajad'
import { Route as MinuKavaRouteImport } from './routes/minu-kava'
import { Route as TagasisideRouteImport } from './routes/tagasiside'
import { Route as SundmusIdRouteImport } from './routes/sundmus.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const KavaRoute = KavaRouteImport.update({
  id: '/kava',
  path: '/kava',
  getParentRoute: () => rootRouteImport,
} as any)
const KoolitajadRoute = KoolitajadRouteImport.update({
  id: '/koolitajad',
  path: '/koolitajad',
  getParentRoute: () => rootRouteImport,
} as any)
const MinuKavaRoute = MinuKavaRouteImport.update({
  id: '/minu-kava',
  path: '/minu-kava',
  getParentRoute: () => rootRouteImport,
} as any)
const TagasisideRoute = TagasisideRouteImport.update({
  id: '/tagasiside',
  path: '/tagasiside',
  getParentRoute: () => rootRouteImport,
} as any)
const SundmusIdRoute = SundmusIdRouteImport.update({
  id: '/sundmus/$id',
  path: '/sundmus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/kava': typeof KavaRoute
  '/koolitajad': typeof KoolitajadRoute
  '/minu-kava': typeof MinuKavaRoute
  '/tagasiside': typeof TagasisideRoute
  '/sundmus/$id': typeof SundmusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/kava': typeof KavaRoute
  '/koolitajad': typeof KoolitajadRoute
  '/minu-kava': typeof MinuKavaRoute
  '/tagasiside': typeof TagasisideRoute
  '/sundmus/$id': typeof SundmusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/kava': typeof KavaRoute
  '/koolitajad': typeof KoolitajadRoute
  '/minu-kava': typeof MinuKavaRoute
  '/tagasiside': typeof TagasisideRoute
  '/sundmus/$id': typeof SundmusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/info'
    | '/kava'
    | '/koolitajad'
    | '/minu-kava'
    | '/tagasiside'
    | '/sundmus/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/info'
    | '/kava'
    | '/koolitajad'
    | '/minu-kava'
    | '/tagasiside'
    | '/sundmus/$id'
  id:
    | '__root__'
    | '/'
    | '/info'
    | '/kava'
    | '/koolitajad'
    | '/minu-kava'
    | '/tagasiside'
    | '/sundmus/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  KavaRoute: typeof KavaRoute
  KoolitajadRoute: typeof KoolitajadRoute
  MinuKavaRoute: typeof MinuKavaRoute
  TagasisideRoute: typeof TagasisideRoute
  SundmusIdRoute: typeof SundmusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kava': {
      id: '/kava'
      path: '/kava'
      fullPath: '/kava'
      preLoaderRoute: typeof KavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koolitajad': {
      id: '/koolitajad'
      path: '/koolitajad'
      fullPath: '/koolitajad'
      preLoaderRoute: typeof KoolitajadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minu-kava': {
      id: '/minu-kava'
      path: '/minu-kava'
      fullPath: '/minu-kava'
      preLoaderRoute: typeof MinuKavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagasiside': {
      id: '/tagasiside'
      path: '/tagasiside'
      fullPath: '/tagasiside'
      preLoaderRoute: typeof TagasisideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sundmus/$id': {
      id: '/sundmus/$id'
      path: '/sundmus/$id'
      fullPath: '/sundmus/$id'
      preLoaderRoute: typeof SundmusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  KavaRoute: KavaRoute,
  KoolitajadRoute: KoolitajadRoute,
  MinuKavaRoute: MinuKavaRoute,
  TagasisideRoute: TagasisideRoute,
  SundmusIdRoute: SundmusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
