/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InfoRouteImport } from './routes/info'
import { Route as KavaRouteImport } from './routes/kava'
import { Route as KoolitajadRouteImport } from './routes/koolitajad'
import { Route as MinuKavaRouteImport } from './routes/minu-kava'
import { Route as PrivaatsusRouteImport } from './routes/privaatsus'
import { Route as TagasisideRouteImport } from './routes/tagasiside'
import { Route as SundmusIdRouteImport } from './routes/sundmus.$id'
import { Route as ApiPublicFientaWebhookRouteImport } from './routes/api/public/fienta-webhook'
import { Route as ApiPublicHooksEvnCleanupRouteImport } from './routes/api/public/hooks/evn-cleanup'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const KavaRoute = KavaRouteImport.update({
  id: '/kava',
  path: '/kava',
  getParentRoute: () => rootRouteImport,
} as any)
const KoolitajadRoute = KoolitajadRouteImport.update({
  id: '/koolitajad',
  path: '/koolitajad',
  getParentRoute: () => rootRouteImport,
} as any)
const MinuKavaRoute = MinuKavaRouteImport.update({
  id: '/minu-kava',
  path: '/minu-kava',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivaatsusRoute = PrivaatsusRouteImport.update({
  id: '/privaatsus',
  path: '/privaatsus',
  getParentRoute: () => rootRouteImport,
} as any)
const TagasisideRoute = TagasisideRouteImport.update({
  id: '/tagasiside',
  path: '/tagasiside',
  getParentRoute: () => rootRouteImport,
} as any)
const SundmusIdRoute = SundmusIdRouteImport.update({
  id: '/sundmus/$id',
  path: '/sundmus/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFientaWebhookRoute = ApiPublicFientaWebhookRouteImport.update({
  id: '/api/public/fienta-webhook',
  path: '/api/public/fienta-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEvnCleanupRoute =
  ApiPublicHooksEvnCleanupRouteImport.update({
    id: '/api/public/hooks/evn-cleanup',
    path: '/api/public/hooks/evn-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/info': typeof InfoRoute
  '/kava': typeof KavaRoute
  '/koolitajad': typeof KoolitajadRoute
  '/minu-kava': typeof MinuKavaRoute
  '/privaatsus': typeof PrivaatsusRoute
  '/tagasiside': typeof TagasisideRoute
  '/sundmus/$id': typeof SundmusIdRoute
  '/api/public/fienta-webhook': typeof ApiPublicFientaWebhookRoute
  '/api/public/hooks/evn-cleanup': typeof ApiPublicHooksEvnCleanupRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/info': typeof InfoRoute
  '/kava': typeof KavaRoute
  '/koolitajad': typeof KoolitajadRoute
  '/minu-kava': typeof MinuKavaRoute
  '/privaatsus': typeof PrivaatsusRoute
  '/tagasiside': typeof TagasisideRoute
  '/sundmus/$id': typeof SundmusIdRoute
  '/api/public/fienta-webhook': typeof ApiPublicFientaWebhookRoute
  '/api/public/hooks/evn-cleanup': typeof ApiPublicHooksEvnCleanupRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/info': typeof InfoRoute
  '/kava': typeof KavaRoute
  '/koolitajad': typeof KoolitajadRoute
  '/minu-kava': typeof MinuKavaRoute
  '/privaatsus': typeof PrivaatsusRoute
  '/tagasiside': typeof TagasisideRoute
  '/sundmus/$id': typeof SundmusIdRoute
  '/api/public/fienta-webhook': typeof ApiPublicFientaWebhookRoute
  '/api/public/hooks/evn-cleanup': typeof ApiPublicHooksEvnCleanupRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/info'
    | '/kava'
    | '/koolitajad'
    | '/minu-kava'
    | '/privaatsus'
    | '/tagasiside'
    | '/sundmus/$id'
    | '/api/public/fienta-webhook'
    | '/api/public/hooks/evn-cleanup'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/info'
    | '/kava'
    | '/koolitajad'
    | '/minu-kava'
    | '/privaatsus'
    | '/tagasiside'
    | '/sundmus/$id'
    | '/api/public/fienta-webhook'
    | '/api/public/hooks/evn-cleanup'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/info'
    | '/kava'
    | '/koolitajad'
    | '/minu-kava'
    | '/privaatsus'
    | '/tagasiside'
    | '/sundmus/$id'
    | '/api/public/fienta-webhook'
    | '/api/public/hooks/evn-cleanup'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  InfoRoute: typeof InfoRoute
  KavaRoute: typeof KavaRoute
  KoolitajadRoute: typeof KoolitajadRoute
  MinuKavaRoute: typeof MinuKavaRoute
  PrivaatsusRoute: typeof PrivaatsusRoute
  TagasisideRoute: typeof TagasisideRoute
  SundmusIdRoute: typeof SundmusIdRoute
  ApiPublicFientaWebhookRoute: typeof ApiPublicFientaWebhookRoute
  ApiPublicHooksEvnCleanupRoute: typeof ApiPublicHooksEvnCleanupRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kava': {
      id: '/kava'
      path: '/kava'
      fullPath: '/kava'
      preLoaderRoute: typeof KavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koolitajad': {
      id: '/koolitajad'
      path: '/koolitajad'
      fullPath: '/koolitajad'
      preLoaderRoute: typeof KoolitajadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minu-kava': {
      id: '/minu-kava'
      path: '/minu-kava'
      fullPath: '/minu-kava'
      preLoaderRoute: typeof MinuKavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privaatsus': {
      id: '/privaatsus'
      path: '/privaatsus'
      fullPath: '/privaatsus'
      preLoaderRoute: typeof PrivaatsusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagasiside': {
      id: '/tagasiside'
      path: '/tagasiside'
      fullPath: '/tagasiside'
      preLoaderRoute: typeof TagasisideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sundmus/$id': {
      id: '/sundmus/$id'
      path: '/sundmus/$id'
      fullPath: '/sundmus/$id'
      preLoaderRoute: typeof SundmusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fienta-webhook': {
      id: '/api/public/fienta-webhook'
      path: '/api/public/fienta-webhook'
      fullPath: '/api/public/fienta-webhook'
      preLoaderRoute: typeof ApiPublicFientaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/evn-cleanup': {
      id: '/api/public/hooks/evn-cleanup'
      path: '/api/public/hooks/evn-cleanup'
      fullPath: '/api/public/hooks/evn-cleanup'
      preLoaderRoute: typeof ApiPublicHooksEvnCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  InfoRoute: InfoRoute,
  KavaRoute: KavaRoute,
  KoolitajadRoute: KoolitajadRoute,
  MinuKavaRoute: MinuKavaRoute,
  PrivaatsusRoute: PrivaatsusRoute,
  TagasisideRoute: TagasisideRoute,
  SundmusIdRoute: SundmusIdRoute,
  ApiPublicFientaWebhookRoute: ApiPublicFientaWebhookRoute,
  ApiPublicHooksEvnCleanupRoute: ApiPublicHooksEvnCleanupRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
