/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KavaRouteImport } from './routes/kava'
import { Route as SundmusIdRouteImport } from './routes/sundmus.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KavaRoute = KavaRouteImport.update({
  id: '/kava',
  path: '/kava',
  getParentRoute: () => rootRouteImport,
} as any)
const SundmusIdRoute = SundmusIdRouteImport.update({
  id: '/sundmus/$id',
  path: '/sundmus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kava': typeof KavaRoute
  '/sundmus/$id': typeof SundmusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kava': typeof KavaRoute
  '/sundmus/$id': typeof SundmusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kava': typeof KavaRoute
  '/sundmus/$id': typeof SundmusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kava' | '/sundmus/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kava' | '/sundmus/$id'
  id: '__root__' | '/' | '/kava' | '/sundmus/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KavaRoute: typeof KavaRoute
  SundmusIdRoute: typeof SundmusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kava': {
      id: '/kava'
      path: '/kava'
      fullPath: '/kava'
      preLoaderRoute: typeof KavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sundmus/$id': {
      id: '/sundmus/$id'
      path: '/sundmus/$id'
      fullPath: '/sundmus/$id'
      preLoaderRoute: typeof SundmusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KavaRoute: KavaRoute,
  SundmusIdRoute: SundmusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
